version: '3'

services:
    selenium:
        image: selenium/standalone-chrome
        ports:
            - "4444:4444"
        restart: always
        networks:
            - mynet
    app:
        build:
            context: .
            dockerfile: dockerfile
        depends_on:
            - selenium

        networks:
            - mynet

networks:
    mynet:

